# Generated by Django 5.1.6 on 2025-08-31 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_analysis', '0002_posttradeanalysis'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='posttradeanalysis',
            new_name='post_analys_trade_i_9bd628_idx',
            old_name='post_analys_trade_i_abc123',
        ),
        migrations.AlterField(
            model_name='posttradeanalysis',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
