# Generated by Django 5.1.6 on 2025-09-01 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_analysis', '0005_allow_multiple_posttradeanalysis_per_trade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posttradeanalysis',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RemoveIndex(
            model_name='posttradeanalysis',
            name='post_analys_trade_i_9bd628_idx',
        ),
    ]
