# Generated by Django 5.1.6 on 2025-09-01 19:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_analysis', '0006_alter_posttradeanalysis_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posttradeanalysis',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Post Trade Analysis', 'verbose_name_plural': 'Post Trade Analyses'},
        ),
        migrations.AddIndex(
            model_name='posttradeanalysis',
            index=models.Index(fields=['trade_id'], name='post_analys_trade_i_9bd628_idx'),
        ),
    ]
