# Generated by Django 5.1.3 on 2026-02-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRecord',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('foods_eaten', models.TextField(blank=True, default='')),
                ('supplements_taken', models.JSONField(blank=True, default=list)),
                ('nutrient_completion', models.JSONField(blank=True, default=dict)),
                ('recommendations', models.TextField(blank=True, default='')),
                ('chat_history', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='LLMConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(default='gemini-3-flash-preview', max_length=255)),
                ('api_key', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('details', models.TextField(blank=True, help_text='What it contains, doses, etc.', null=True)),
            ],
        ),
    ]
