# Generated by Django 5.1.3 on 2026-02-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrients_tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('details', models.TextField(blank=True, help_text='Macros, portions, etc.', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='llmconfig',
            name='user_profile',
            field=models.TextField(blank=True, default='', help_text='Age, weight, daily activities, etc.'),
        ),
    ]
