# Generated by Django 5.1.3 on 2026-02-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrients_tracker', '0002_fooditem_llmconfig_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmconfig',
            name='available_models',
            field=models.TextField(blank=True, default='gemini-3-flash-preview,gemini-1.5-pro-preview-0409', help_text='Comma-separated list of models'),
        ),
    ]
