# Generated by Django 5.1.3 on 2026-02-23 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrients_tracker', '0003_llmconfig_available_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrecord',
            name='nutrient_sources',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
