# Generated by Django 5.1.3 on 2026-02-15 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('column_key', models.CharField(max_length=100, unique=True)),
                ('position', models.IntegerField(default=0)),
                ('is_custom', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='CustomColumn',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CustomColumnValue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trade_id', models.IntegerField()),
                ('value', models.TextField(blank=True, default='')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='custom_trade_data_tracking.customcolumn')),
            ],
            options={
                'ordering': ['trade_id', 'column'],
                'unique_together': {('trade_id', 'column')},
            },
        ),
    ]
