# Generated by Django 5.1.3 on 2026-02-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_trade_data_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='columnorder',
            name='width',
            field=models.IntegerField(default=0),
        ),
    ]
