# Generated by Django 5.1.3 on 2026-02-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_trade_data_tracking', '0002_columnorder_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='columnorder',
            name='is_textarea',
            field=models.BooleanField(default=False),
        ),
    ]
