"""
Django settings for djangoProject project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Static files settings
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MICROSERVICE_URL = os.getenv('FLASK_SERVICE_URL', 'http://localhost:5000')
print(f"Using microservice URL: {MICROSERVICE_URL}")  # Temporary debug line

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-sq7&3x(!x#wi$&c=qrtp45qd&a7i2yhnhcwac113p_c3m#(2mv"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "Stocks_Filtering_App.apps.StocksFilteringAppConfig",
    "corsheaders",
    "personal_ranking_list_app",
    "rest_framework",
    "trades_history",
    "post_analysis",
    "price_alerts",
    "hosted_backend_config",
    "custom_trade_data_tracking",
    "violations_monitor",
    "nutrients_tracker",
    "ticker_data",
]

MICROSERVICE_SETTINGS = {
    'FLASK_SERVICE_URL': MICROSERVICE_URL,
    'TIMEOUT': 30,  # seconds
    'VERIFY_SSL': True,
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
]

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [],
    'DEFAULT_PERMISSION_CLASSES': [],
}

ROOT_URLCONF = "djangoProject.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates']
        ,
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "djangoProject.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "dbs/db.sqlite3",
    },
    'personal_ranking': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'dbs/personal_ranking.sqlite3',
    },
    'trades_db': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'dbs/trades_db.sqlite3',
    },
    'price_alerts_db': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'dbs/price_alerts.sqlite3',
    },
    'telegram_config_db': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'dbs/telegram_config.sqlite3',
    },
    'hosted_backend_db': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'dbs/hosted_backend.sqlite3',
    },
    'post_analysis_recommendations': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'dbs/post_analysis_recommendations.sqlite3',
    },
    'custom_trade_data_tracking_db': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'dbs/custom_trade_data_tracking.sqlite3',
    },
    'violations_monitor_db': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'dbs/violations_monitor.sqlite3',
    },
    'nutrients_tracker_db': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'dbs/nutrients_tracker.sqlite3',
    },
    'ticker_data_db': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'dbs/ticker_data.sqlite3',
        'OPTIONS': {
            'timeout': 30,
        },
    }
}

DATABASE_ROUTERS = [
    'personal_ranking_list_app.router.PersonalRankingRouter',
    'trades_history.router.TradesRouter',
    'post_analysis.router.PostAnalysisRouter',
    'price_alerts.router.PriceAlertsRouter',
    'price_alerts.telegram_router.TelegramConfigRouter',
    'hosted_backend_config.router.HostedBackendRouter',
    'custom_trade_data_tracking.router.CustomTradeDataRouter',
    'violations_monitor.router.ViolationsMonitorRouter',
    'nutrients_tracker.router.NutrientsTrackerRouter',
    'ticker_data.router.TickerDataRouter',
]

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
