# Generated by Django 5.1.3 on 2025-01-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal_ranking_list_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockcharacteristic",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
