# Generated by Django 5.1.3 on 2025-01-01 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal_ranking_list_app", "0002_stockcharacteristic_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpagestate",
            name="ranking_boxes_order",
            field=models.TextField(default="[]"),
        ),
    ]
