# Generated by Django 5.1.6 on 2025-02-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_ranking_list_app', '0003_userpagestate_ranking_boxes_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockpick',
            name='case_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
