# Generated by Django 5.1.6 on 2025-04-06 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_ranking_list_app', '0004_stockpick_case_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('default_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='stockcharacteristic',
            unique_together={('stock_pick', 'name')},
        ),
        migrations.AddField(
            model_name='stockcharacteristic',
            name='global_characteristic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_characteristics', to='personal_ranking_list_app.globalcharacteristic'),
        ),
        migrations.RemoveField(
            model_name='stockcharacteristic',
            name='description',
        ),
    ]

