# Generated by Django 5.1.6 on 2025-04-06 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_ranking_list_app', '0006_remove_globalcharacteristic_default_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalcharacteristic',
            name='score',
        ),
        migrations.RemoveField(
            model_name='stockpickcharacteristic',
            name='custom_score',
        ),
        migrations.AddField(
            model_name='globalcharacteristic',
            name='default_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockpickcharacteristic',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stockpickcharacteristic',
            name='characteristic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_assignments', to='personal_ranking_list_app.globalcharacteristic'),
        ),
        migrations.AlterField(
            model_name='stockpickcharacteristic',
            name='stockpick',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_characteristics', to='personal_ranking_list_app.stockpick'),
        ),
    ]
