# Generated by Django 5.1.6 on 2025-04-06 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_ranking_list_app', '0007_remove_globalcharacteristic_score_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockpickcharacteristic',
            unique_together=set(),
        ),
    ]
