# Generated by Django 5.1.6 on 2025-04-06 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_ranking_list_app', '0008_alter_stockpickcharacteristic_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockpickcharacteristic',
            unique_together={('stockpick', 'characteristic')},
        ),
    ]
