# Generated by Django 5.1.6 on 2025-04-06 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_ranking_list_app', '0009_alter_stockpickcharacteristic_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockpick',
            name='personal_opinion_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
