# Generated by Django 5.1.6 on 2025-04-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_ranking_list_app', '0010_stockpick_personal_opinion_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockpick',
            name='demand_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
