# Generated by Django 5.1.6 on 2025-04-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_ranking_list_app', '0011_stockpick_demand_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockpick',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockpick',
            name='case_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockpick',
            name='demand_reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stockpick',
            name='personal_opinion_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stockpick',
            name='total_score',
            field=models.FloatField(default=0),
        ),
    ]
