# Generated by Django 5.1.3 on 2025-09-30 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_ranking_list_app', '0012_stockpick_note_alter_stockpick_case_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorCodedCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('characteristic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='color_coded_meta', to='personal_ranking_list_app.globalcharacteristic')),
            ],
        ),
        migrations.CreateModel(
            name='OrderedCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(help_text='Lower numbers appear first')),
                ('characteristic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_meta', to='personal_ranking_list_app.globalcharacteristic')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='PriorityCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('characteristic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='priority_meta', to='personal_ranking_list_app.globalcharacteristic')),
            ],
        ),
    ]
