# Generated by Django 5.1.3 on 2025-12-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_alerts', '0002_telegramconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='percent_change',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='previous_close',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
