# Generated by Django 5.1.3 on 2025-12-24 22:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_alerts', '0003_alert_percent_change_alert_previous_close'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='fetch_interval_ms',
            field=models.IntegerField(default=1000, validators=[django.core.validators.MinValueValidator(500)]),
        ),
    ]
