# Generated by Django 5.1.4 on 2025-02-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Trades",
            fields=[
                ("ID", models.IntegerField(primary_key=True, serialize=False)),
                ("Ticker", models.CharField(max_length=10)),
                ("Status", models.CharField(max_length=50)),
                ("Entry_Date", models.DateField()),
                ("Exit_Date", models.DateField(blank=True, null=True)),
                ("Entry_Price", models.FloatField()),
                ("Exit_Price", models.FloatField(blank=True, null=True)),
                ("Pattern", models.CharField(max_length=100)),
                ("Days_In_Pattern_Before_Entry", models.IntegerField()),
                ("Price_Tightness_1_Week_Before", models.FloatField()),
                ("Exit_Reason", models.CharField(max_length=200)),
                ("Market_Condition", models.CharField(max_length=100)),
                ("Category", models.CharField(max_length=100)),
                ("Earnings_Quality", models.IntegerField()),
                ("Fundamentals_Quality", models.BooleanField()),
                ("Has_Earnings_Acceleration", models.BooleanField()),
                ("Has_Catalyst", models.BooleanField()),
                ("Earnings_Last_Q_20_Pct", models.BooleanField()),
                ("IPO_Last_10_Years", models.BooleanField()),
                ("Nr_Bases", models.IntegerField()),
                ("Volume_Confirmation", models.BooleanField()),
                ("Is_BioTech", models.BooleanField()),
                ("Earnings_Surprises", models.BooleanField(default=False)),
                ("Expanding_Margins", models.BooleanField(default=False)),
                ("EPS_breakout", models.BooleanField(default=False)),
                ("Strong_annual_EPS", models.BooleanField(default=False)),
                (
                    "Signs_Acceleration_Will_Continue",
                    models.BooleanField(default=False),
                ),
                ("Sudden_Growth_Change", models.BooleanField(default=False)),
                (
                    "Strong_Quarterly_And_Yearly_Sales",
                    models.BooleanField(default=False),
                ),
                ("Positive_Analysts_Revisions", models.BooleanField(default=False)),
                (
                    "Ownership_Pct_Change_Past_Earnings",
                    models.BooleanField(default=False),
                ),
                ("Quarters_With_75pct_Surprise", models.BooleanField(default=False)),
                ("Over_10_pct_Avg_Surprise", models.BooleanField(default=False)),
            ],
        ),
    ]
