# Generated by Django 5.1.4 on 2025-02-05 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trades_history", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trades",
            name="EPS_breakout",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="trades",
            name="Earnings_Surprises",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="trades",
            name="Expanding_Margins",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="trades",
            name="Over_10_pct_Avg_Surprise",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="trades",
            name="Ownership_Pct_Change_Past_Earnings",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="trades",
            name="Positive_Analysts_Revisions",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="trades",
            name="Quarters_With_75pct_Surprise",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="trades",
            name="Signs_Acceleration_Will_Continue",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="trades",
            name="Strong_Quarterly_And_Yearly_Sales",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="trades",
            name="Strong_annual_EPS",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="trades",
            name="Sudden_Growth_Change",
            field=models.BooleanField(),
        ),
    ]
