# Generated by Django 5.1.6 on 2025-02-08 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades_history', '0002_alter_trades_eps_breakout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trades',
            name='Fundamentals_Quality',
            field=models.IntegerField(),
        ),
    ]
