# Generated by Django 5.1.6 on 2025-02-08 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades_history', '0003_alter_trades_fundamentals_quality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trades',
            name='Exit_Reason',
            field=models.CharField(max_length=1000),
        ),
    ]
