# Generated by Django 5.1.6 on 2025-02-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades_history', '0005_trades_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='trades',
            name='Under_30M_Shares',
            field=models.BooleanField(default=False),
        ),
    ]
