# Generated by Django 5.1.6 on 2025-02-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades_history', '0006_trades_under_30k_shares'),
    ]

    operations = [
        migrations.AddField(
            model_name='trades',
            name='Spikes_On_Volume',
            field=models.BooleanField(default=False),
        ),
    ]
