# Generated by Django 5.1.6 on 2025-03-17 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades_history', '0007_trades_spikes_on_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='trades',
            name='Started_Off_Corrections',
            field=models.BooleanField(default=False),
        ),
    ]
