# Generated by Django 5.1.6 on 2025-03-17 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades_history', '0008_trades_started_off_corrections'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trades',
            old_name='Started_Off_Corrections',
            new_name='Started_Off_Correction',
        ),
    ]
