# Generated by Django 5.1.6 on 2025-03-17 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades_history', '0009_rename_started_off_corrections_trades_started_off_correction'),
    ]

    operations = [
        migrations.AddField(
            model_name='trades',
            name='Return',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
