# Generated by Django 5.1.6 on 2025-03-30 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades_history', '0011_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trades',
            old_name='Positive_Analysts_Revisions',
            new_name='Positive_Analysts_EPS_Revisions',
        ),
    ]
