# Generated by Django 5.1.6 on 2025-03-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades_history', '0012_rename_positive_analysts_revisions_trades_positive_analysts_eps_revisions'),
    ]

    operations = [
        migrations.AddField(
            model_name='trades',
            name='Positive_Analysts_Price_Revisions',
            field=models.BooleanField(default=False),
        ),
    ]
