# Generated by Django 5.1.6 on 2025-03-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades_history', '0013_trades_positive_analysts_price_revisions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trades',
            old_name='Strong_Quarterly_And_Yearly_Sales',
            new_name='Strong_Quarterly_Sales',
        ),
        migrations.AddField(
            model_name='trades',
            name='Strong_Yearly_Sales',
            field=models.BooleanField(default=False),
        ),
    ]
