# Generated by Django 5.1.6 on 2025-04-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades_history', '0014_rename_strong_quarterly_and_yearly_sales_trades_strong_quarterly_sales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trades',
            name='All_Trendlines_Up',
            field=models.BooleanField(default=False),
        ),
    ]
