# Generated by Django 5.1.6 on 2025-05-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades_history', '0015_trades_all_trendlines_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='trades',
            name='Pct_Off_52W_High',
            field=models.FloatField(default=100),
        ),
    ]
