# Generated by Django 5.1.6 on 2025-06-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades_history', '0016_trades_pct_off_52w_high'),
    ]

    operations = [
        migrations.AddField(
            model_name='trades',
            name='If_You_Could_Only_Make_10_Trades',
            field=models.BooleanField(default=False),
        ),
    ]
