# Generated by Django 5.1.6 on 2025-06-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('trades_history', '0017_trades_if_you_could_only_make_10_trades'),
    ]

    operations = [
        # First, make all fields nullable to avoid constraint issues
        migrations.AlterField(
            model_name='trades',
            name='All_Trendlines_Up',
            field=models.BooleanField(null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='trades',
            name='Days_In_Pattern_Before_Entry',
            field=models.IntegerField(null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='trades',
            name='EPS_breakout',
            field=models.BooleanField(null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='trades',
            name='Earnings_Last_Q_20_Pct',
            field=models.BooleanField(null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='trades',
            name='Earnings_Quality',
            field=models.IntegerField(null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='trades',
            name='Earnings_Surprises',
            field=models.BooleanField(null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='trades',
            name='Expanding_Margins',
            field=models.BooleanField(null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='trades',
            name='Fundamentals_Quality',
            field=models.IntegerField(null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='trades',
            name='Over_10_pct_Avg_Surprise',
            field=models.BooleanField(null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='trades',
            name='Ownership_Pct_Change_Past_Earnings',
            field=models.BooleanField(null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='trades',
            name='Positive_Analysts_EPS_Revisions',
            field=models.BooleanField(null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='trades',
            name='Positive_Analysts_Price_Revisions',
            field=models.BooleanField(null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='trades',
            name='Quarters_With_75pct_Surprise',
            field=models.BooleanField(null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='trades',
            name='Spikes_On_Volume',
            field=models.BooleanField(null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='trades',
            name='Started_Off_Correction',
            field=models.BooleanField(null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='trades',
            name='Strong_Quarterly_Sales',
            field=models.BooleanField(null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='trades',
            name='Strong_Yearly_Sales',
            field=models.BooleanField(null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='trades',
            name='Sudden_Growth_Change',
            field=models.BooleanField(null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='trades',
            name='Volume_Confirmation',
            field=models.BooleanField(null=True, blank=True),
        ),

        # Now safely remove all the fields
        migrations.RemoveField(
            model_name='trades',
            name='All_Trendlines_Up',
        ),
        migrations.RemoveField(
            model_name='trades',
            name='Days_In_Pattern_Before_Entry',
        ),
        migrations.RemoveField(
            model_name='trades',
            name='EPS_breakout',
        ),
        migrations.RemoveField(
            model_name='trades',
            name='Earnings_Last_Q_20_Pct',
        ),
        migrations.RemoveField(
            model_name='trades',
            name='Earnings_Quality',
        ),
        migrations.RemoveField(
            model_name='trades',
            name='Earnings_Surprises',
        ),
        migrations.RemoveField(
            model_name='trades',
            name='Expanding_Margins',
        ),
        migrations.RemoveField(
            model_name='trades',
            name='Fundamentals_Quality',
        ),
        migrations.RemoveField(
            model_name='trades',
            name='Over_10_pct_Avg_Surprise',
        ),
        migrations.RemoveField(
            model_name='trades',
            name='Ownership_Pct_Change_Past_Earnings',
        ),
        migrations.RemoveField(
            model_name='trades',
            name='Positive_Analysts_EPS_Revisions',
        ),
        migrations.RemoveField(
            model_name='trades',
            name='Positive_Analysts_Price_Revisions',
        ),
        migrations.RemoveField(
            model_name='trades',
            name='Quarters_With_75pct_Surprise',
        ),
        migrations.RemoveField(
            model_name='trades',
            name='Spikes_On_Volume',
        ),
        migrations.RemoveField(
            model_name='trades',
            name='Started_Off_Correction',
        ),
        migrations.RemoveField(
            model_name='trades',
            name='Strong_Quarterly_Sales',
        ),
        migrations.RemoveField(
            model_name='trades',
            name='Strong_Yearly_Sales',
        ),
        migrations.RemoveField(
            model_name='trades',
            name='Sudden_Growth_Change',
        ),
        migrations.RemoveField(
            model_name='trades',
            name='Volume_Confirmation',
        ),
    ]