# Generated by Django 5.1.6 on 2025-08-31 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades_history', '0018_safe_field_removal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trades',
            name='Has_Catalyst',
        ),
        migrations.RemoveField(
            model_name='trades',
            name='Signs_Acceleration_Will_Continue',
        ),
        migrations.RemoveField(
            model_name='trades',
            name='Strong_annual_EPS',
        ),
        migrations.AddField(
            model_name='trades',
            name='A',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trades',
            name='C',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trades',
            name='I',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trades',
            name='L',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trades',
            name='M',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trades',
            name='N',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trades',
            name='S',
            field=models.BooleanField(default=False),
        ),
    ]
