# Generated by Django 5.1.3 on 2026-03-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades_history', '0019_remove_trades_has_catalyst_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trades',
            name='Pct_Of_Equity',
            field=models.FloatField(default=0, help_text='Position size as percentage of total equity (0-100)'),
        ),
    ]
