# Generated by Django 5.1.3 on 2026-03-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providersettings',
            name='fetch_outside_hours',
        ),
        migrations.RemoveField(
            model_name='providersettings',
            name='max_requests_per_second',
        ),
        migrations.AddField(
            model_name='providersettings',
            name='max_requests_per_10s',
            field=models.FloatField(default=20.0, help_text='Max permitted requests per 10 seconds.'),
        ),
    ]
