# Generated by Django 5.1.3 on 2026-03-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker_data', '0003_add_ingested_at_to_price_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providersettings',
            name='max_requests_per_10s',
            field=models.FloatField(default=10.0, help_text='Max permitted requests per 10 seconds.'),
        ),
    ]
